# This file contains the secret for database credentials, nominally should be excluded from the repository.
apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
type: Opaque
data:
  PGHOST: cG9zdGdyZXMtc2VydmljZQ== # base64 encoded value of postgres-service
  PGUSER: bXl1c2Vy # base64 encoded value of myuser
  PGPASSWORD: bXlwYXNzd29yZA== # base64 encoded value of mypassword
  PGDATABASE: bXlkYg== # base64 encoded value of mydb
