apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nodejs-app
  labels:
    app: nodejs-app
    tier: backend
  annotations:
    description: "Node.js application ReplicaSet"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodejs-app
  template:
    metadata:
      labels:
        app: nodejs-app
        tier: backend
      annotations:
        description: "Node.js application Pod"
    spec:
      containers:
        - name: nodejs-app
          image: nodejs-app:latest # us-central1-docker.pkg.dev/[YOUR_PROJECT_ID]/nodejs-app-repo/nodejs-app:latest
          imagePullPolicy: Never # use the local image
          ports:
            - containerPort: 3000
          envFrom:
            - secretRef:
                name: db-credentials
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5

# kubectl apply -f nodejs-replicaset.yml
