apiVersion: v1
kind: Service
metadata:
  name: nodejs-local-service
spec:
  type: LoadBalancer
  selector:
    app: nodejs-app
  ports:
    - port: 3000
      targetPort: 3000

# kubectl get pods --show-labels
# kubectl apply -f nodejs-service.yml
